version: "3"
services:
  nginx:
    image: nginx:latest
    stdin_open: true
    tty: true
    ports:
      - 80:80
    volumes:
      - 'nfsmount:/var/doodle'
      - ./.docker/vhost.conf:/etc/nginx/conf.d/default.conf:delegated
    depends_on:
      - php

  php:
    build: '.docker/'
    volumes:
      - 'nfsmount:/var/doodle'


volumes:
  nfsmount:
    driver: local
    driver_opts:
      type: nfs
      o: addr=host.docker.internal,rw,nolock,hard,nointr,nfsvers=3
      device: ":${PWD}"