version: '3'

services:
  nginx:
    image: nginx:1.17
    restart: always
    ports:
      - 80:80
    volumes:
      - ./src:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    working_dir: /usr/share/nginx/html

  php:
    build: ./php
    restart: always
    volumes:
      - ./src:/usr/share/nginx/html
    working_dir: /usr/share/nginx/html